# Generated by Django 5.0.2 on 2024-03-04 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media_api", "0005_alter_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="profile",
        ),
        migrations.AddField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
