# Generated by Django 5.0.2 on 2024-03-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media_api", "0006_remove_user_profile_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="date_of_birth",
            field=models.DateField(null=True),
        ),
    ]
