# Generated by Django 5.0.2 on 2024-03-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media_api", "0008_remove_profile_user_user_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="follows",
            field=models.ManyToManyField(
                blank=True, related_name="followed_by", to="social_media_api.profile"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.URLField(
                default="https://media.istockphoto.com/id/1354776457/vector/default-image-icon-vector-missing-picture-page-for-website-design-or-mobile-app-no-photo.jpg?s=612x612&w=0&k=20&c=w3OW0wX3LyiFRuDHo9A32Q0IUMtD4yjXEvQlqyYk9O4=",
                max_length=255,
            ),
        ),
    ]
