# Generated by Django 5.0.2 on 2024-03-05 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media_api", "0010_post_profile_posts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="posts",
        ),
        migrations.AddField(
            model_name="post",
            name="profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="social_media_api.profile",
            ),
        ),
    ]
