# Generated by Django 5.0.2 on 2024-03-05 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media_api", "0011_remove_profile_posts_post_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="social_media_api.profile",
            ),
        ),
    ]
