# Generated by Django 5.0.2 on 2024-03-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media_api", "0012_alter_post_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="hashtags",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
